# Generated by Django 5.1.3 on 2024-12-08 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
        ('identity_card', '0011_alter_identitycard_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequestidc',
            name='identity_card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity_card.identitycard'),
        ),
    ]
