# Generated by Django 5.1.3 on 2024-11-27 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=65)),
                ('number', models.CharField(default='ya77OusgJmB1', max_length=12)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=50)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(default=datetime.datetime(2034, 11, 24, 19, 12, 45, 405918))),
            ],
        ),
    ]
