# Generated by Django 5.1.3 on 2024-12-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_card', '0011_alter_identitycard_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitycard',
            name='status',
            field=models.BooleanField(choices=[(False, 'INACTIVE'), (True, 'ACTIVE')], default=False),
        ),
        migrations.AddField(
            model_name='passport',
            name='status',
            field=models.BooleanField(choices=[(False, 'INACTIVE'), (True, 'ACTIVE')], default=False),
        ),
    ]
